<?xml version="1.0"?>
<package format="3">
  <name>polebot_control</name>
  <version>0.1.0</version>
  <description>Custom control logic and odometry for AMR-POLEBOT (C++ + Python)</description>
  <maintainer email="polman@polman-bandung.ac.id">MiraeNK</maintainer>
  <license>Apache-2.0</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>rclcpp</depend>
  <depend>rclpy</depend>
  <depend>std_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>tf2</depend>
  <depend>tf2_ros</depend>
  <depend>polebot_interfaces</depend>
  <export><build_type>ament_cmake</build_type></export>
</package>
