<?xml version="1.0"?>
<package format="3">
  <name>polebot_teleop</name>
  <version>0.1.0</version>
  <description>Keyboard and joystick teleoperation for AMR-POLEBOT</description>
  <maintainer email="polman@polman-bandung.ac.id">MiraeNK</maintainer>
  <license>Apache-2.0</license>
  <depend>rclpy</depend>
  <depend>geometry_msgs</depend>
  <exec_depend>joy</exec_depend>
  <exec_depend>teleop_twist_joy</exec_depend>
  <buildtool_depend>ament_python</buildtool_depend>
  <export><build_type>ament_python</build_type></export>
</package>
