<?xml version="1.0"?>
<package format="3">
  <name>polebot_sensors</name>
  <version>0.1.0</version>
  <description>Sensor drivers configuration for AMR-POLEBOT (LiDAR, IMU, Camera)</description>
  <maintainer email="polman@polman-bandung.ac.id">MiraeNK</maintainer>
  <license>Apache-2.0</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>rplidar_ros</exec_depend>
  <exec_depend>imu_tools</exec_depend>
  <exec_depend>v4l2_camera</exec_depend>
  <export><build_type>ament_cmake</build_type></export>
</package>
