<?xml version="1.0"?>
<package format="3">
  <name>polebot_slam</name>
  <version>0.1.0</version>
  <description>SLAM Toolbox configuration for AMR-POLEBOT mapping</description>
  <maintainer email="polman@polman-bandung.ac.id">MiraeNK</maintainer>
  <license>Apache-2.0</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>slam_toolbox</exec_depend>
  <export><build_type>ament_cmake</build_type></export>
</package>
